models:
  embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
  chatbot_model: "mistral_7b"

data:
  default_faqs: "data/default_faqs.csv"
  uploaded_faqs: "data/uploaded_faqs.csv"
  embeddings: "data/embeddings"
  default_faqs_embedddings: "data/embeddings/default_faqs_embeddings.bin"
  uploaded_faqs_embedddings: "data/embeddings/uploaded_faqs_embeddings.bin"
